services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: mssql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - TZ=Europe/Bucharest
      - MSSQL_SA_PASSWORD=SuperPass#
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $${MSSQL_SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


volumes:
  mssql_data:
