services:

  #ingress controller
  traefik:
    image: "traefik:latest"
    container_name: traefik
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping"
      - "--accesslog=false"
      - "--entrypoints.web=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=false"
    ports:
     - 80:80
     - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localenv.io`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal

      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Updates images
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Bucharest
      - WATCHTOWER_POLL_INTERVAL=21600
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - com.centurylinklabs.watchtower.enable=true

 

networks:
  default:
    name: localenv